import { NextResponse } from 'next/server';
import { generateImageWithFallback, ImageGenConfig } from '@/lib/image-generation-service';

export async function POST(request: Request) {
  try {
    const { prompt, negativePrompt, width, height, apiConfig } = await request.json();

    if (!prompt) {
      return NextResponse.json(
        { error: 'Требуется prompt для генерации изображения' },
        { status: 400 }
      );
    }

    console.log('🎨 Generating image with prompt:', prompt);

    // Use API config from request if provided
    const config: ImageGenConfig = apiConfig || {};

    // Use new image generation service with fallback
    const { imageUrl, source } = await generateImageWithFallback({
      prompt,
      negativePrompt: negativePrompt || 'low quality, blurry, distorted, deformed, ugly',
      width: width || 512,
      height: height || 512,
      steps: 20,
      cfgScale: 7,
    }, config);

    console.log(`✅ Image generated by: ${source}`);

    return NextResponse.json({ 
      imageUrl,
      source // Возвращаем источник для отладки
    });
  } catch (error) {
    console.error('Ошибка генерации изображения:', error);
    return NextResponse.json(
      { error: 'Не удалось сгенерировать изображение' },
      { status: 500 }
    );
  }
}